version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: typed-ast
    versions:
    - 1.4.3
  - dependency-name: pyotp
    versions:
    - 2.5.1
