pull_request_rules:
- name: Automatic merge on approval
  actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/authdev
  - "#approved-reviews-by>=1"
  - status-success=DCO
  - status-success=lint
  - status-success=format
  - status-success=licenses
  - status-success=bandit
  - status-success=py36-unittest
  - status-success=py36-integration
  - status-success=py37-unittest
  - status-success=py37-integration
