---
- name: Install RPM packages
  dnf:
      name: ['git', 'vim', 'poetry', 'python3-flask', 'python3-pip', 'python3-cryptography', 'freeipa-server', 'fedora-messaging']
      state: present

- name: install python deps with poetry
  shell: poetry install
  become: yes
  become_user: vagrant
  args:
    chdir: /vagrant/

- name: uninstall existing freeipa server
  shell: test -f /var/log/ipaserver-install.log && ipa-server-install --uninstall --unattended
  ignore_errors: yes

- name: install freeipa server
  shell: umask 022; ipa-server-install -a adminPassw0rd! --hostname=ipa.noggin.test -r NOGGIN.TEST -p adminPassw0rd! -n noggin.test -U

- name: get freeipa-fas
  git:
    repo: https://github.com/fedora-infra/freeipa-fas.git
    dest: /home/vagrant/freeipa-fas

- name: install freeipa-fas
  shell: ./install.sh
  args:
    chdir: /home/vagrant/freeipa-fas/

- name: Install the .bashrc
  copy:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: Install noggin.cfg
  copy:
      src: /vagrant/noggin.cfg.default
      dest: /home/vagrant/noggin.cfg
      remote_src: yes
      owner: vagrant
      group: vagrant

- name: create backup of clean FreeIPA server data
  shell: ipa-backup


# ipa-backup creates the backup with a datetime in the dirname. here
# we just copy it to noggin-clean so we can reference it easier in the 
# bash alias.
- name: copy clean backup
  shell: mv /var/lib/ipa/backup/ipa-full* /var/lib/ipa/backup/noggin-clean


- name: Create dummy freeipa data
  shell: poetry run python /vagrant/devel/create-test-data.py
  become: yes
  become_user: vagrant

- name: compile the translations
  shell: poetry run pybabel compile -d /vagrant/noggin/translations
  become: yes
  become_user: vagrant

- name: Install the systemd unit files for noggin services
  copy:
      src: "{{ item }}"
      dest: /etc/systemd/system/{{ item }}
      mode: 0644
  with_items:
      - noggin.service

- name: Start noggin service using systemd
  systemd:
    state: started
    name: noggin
    daemon_reload: yes
    enabled: yes

- import_tasks: rabbitmq.yml
